### ISSUE TITLE
Default make that libQt5WebEngine.so in not found by ld.so

### ISSUE THREAD

**Issue by hfiguiere** [flathub/io.qt.qtwebengine.BaseApp#1]
By default ld.so will not find libQt5WebEngine.so.

**Comment by aleixpol** [comment]
Can you please provided some more information? It always worked when testing.

**Comment by hfiguiere** [comment]
```
mscore: error while loading shared libraries: libQt5WebEngineWidgets.so.5: cannot open shared object file: No such file or directory
```

Because it is in a `/app/lib` subdirectory.

This is from the branch https://github.com/hfiguiere/org.musescore.MuseScore/tree/5.13

**Comment by hfiguiere** [comment]
BTW, I know I can use LD_LIBRARY_PATH but it would be better to not have to

**Comment by jurf** [comment]
Also, PyQtWebengine doesn’t find the module by default either.

**Comment by Erick555** [comment]
> BTW, I know I can use LD_LIBRARY_PATH but it would be better to not have to

It's up to your app where it looks for libs so it can't be fixed here. Using `LD_LIBRARY_PATH` is fine and many apps do it: https://github.com/search?q=org%3Aflathub+LD_LIBRARY_PATH&type=Code

**Comment by TingPing** [comment]
The KDE runtime could just modify its ldconfig to include this path.

**Comment by aleixpol** [comment]
@rinigus @grulja Any idea why this wasn't solved by https://github.com/flathub/io.qt.qtwebengine.BaseApp/pull/3?

@TingPing any example of another project that modifies ldconfig to add a path?

**Comment by rinigus** [comment]
@aleixpol : but it is solved for Angelfish and 5.14 with #3. Where is it causing issues? Maybe in 5.13 - there it's not included (branch/5.13)

**Comment by eszlari** [comment]
I guess this is now fixed for both, [cmake](https://github.com/flathub/io.qt.qtwebengine.BaseApp/pull/3) and [qmake](https://github.com/flathub/io.qt.qtwebengine.BaseApp/pull/6)?

**Comment by hfiguiere** [comment]
With https://github.com/flathub/org.musescore.MuseScore/pull/56 is works. (update to 5.14 for MuseScore)

**Comment by aleixpol** [comment]
Good stuff, thanks for the fixes!
