### ISSUE TITLE
QtWebEngineProcess - core dump

### ISSUE THREAD

**Issue by fedelibre** [flathub/io.qt.qtwebengine.BaseApp#11]
I'm using version 5.15. Here's the error I get:

```
[📦 io.qt.qtwebengine.BaseApp ~]$ QtWebEngineProcess 
QWebEngine: OpenGL resource sharing is not set up in QtQuick. Please make sure to call QtWebEngine::initialize() in your main() function.
QWebEngine: OpenGL resource sharing is not set up in QtQuick. Please make sure to call QtWebEngine::initialize() in your main() function.
QWebEngine: OpenGL resource sharing is not set up in QtQuick. Please make sure to call QtWebEngine::initialize() in your main() function.
QWebEngine: OpenGL resource sharing is not set up in QtQuick. Please make sure to call QtWebEngine::initialize() in your main() function.
QWebEngine: OpenGL resource sharing is not set up in QtQuick. Please make sure to call QtWebEngine::initialize() in your main() function.
QWebEngine: OpenGL resource sharing is not set up in QtQuick. Please make sure to call QtWebEngine::initialize() in your main() function.
[31:37:1222/224428.934317:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

For the records, here's the [original issue in the app I'm maintaining](https://github.com/flathub/org.frescobaldi.Frescobaldi/issues/1). I thought the error depended on me, then someone made me realize that QtWebEngineProcess is part of this app.

Let me know if you need more info to debug it.

**Comment by tinywrkb** [comment]
@fedelibre can this be closed?  
If not, then please try with the `5.15-21.08` branch. The `5.15` branch is not maintained anymore, or at least I'm not sending PRs to update it.

**Comment by fedelibre** [comment]
Yes, I think we can close it.

I fixed the issue adding `--env=QTWEBENGINEPROCESS_PATH=/app/bin/QtWebEngineProcess`, see [this](https://github.com/flathub/org.frescobaldi.Frescobaldi/issues/1#issuecomment-749821318).

**Comment by tinywrkb** [comment]
Great!
