### ISSUE TITLE
Grant `travier` access

### ISSUE THREAD

**Issue by travier** [flathub/io.qt.qtwebengine.BaseApp#113]
I'm working on the 22.08 Runtime update for KDE. Can I be granted access to this repo?

Thanks!

**Comment by tinywrkb** [comment]
You need to ping someone who has admin access here. Try posting in the Matrix room.  
If you're adding 22.08 based branches, ~~then maybe hold off Qt6 one until 6.4 will be out, it would be nice not having to maintain multiple Qt6 based branches~~ (edit: forgot it needs an appropriate KDE runtime branch). For the record, I don't have merging powers here, and I'm not eager to have such.  
You should be able to switch to system libxml, now that it's built with ICU enabled, and in the Qt5 based branch this also means  dropping the patch that fixes in-tree libxml.

**Comment by travier** [comment]
Thanks. I've started with a pull request and will ask someone else to push it once ready.
