### ISSUE TITLE
6.4 branch

### ISSUE THREAD

**Issue by JakobDev** [flathub/io.qt.qtwebengine.BaseApp#124]
Would be nice, to have this BaseApp available for the 6.4 runtime

**Comment by hfiguiere** [comment]
would be nice. 

patches need to be rebased.

**Comment by JakobDev** [comment]
@hfiguiere Can you do that? I have n experience in building and patching something like this and you have also created the Patches for 5.15-22.08.

**Comment by hfiguiere** [comment]
created the branch

**Comment by JakobDev** [comment]
It's a bit late, cause 6.5 is now out. There are only little changes on the files, that are affected by the patches, so I was apply to get then work for 6.5 (this means just, that `git apply` don't throw an error any more) and created #196. I hope it works.

If anyone reading this interested: The PR for 6.4 was #159
