### ISSUE TITLE
Is the 5.15 branch outdated?

### ISSUE THREAD

**Issue by tinywrkb** [flathub/io.qt.qtwebengine.BaseApp#14]
Does the Qt 5.12.2 in the runtime really forces us to stick with the outdated QtWebEngine 5.15.2 version that has multiple CVEs? or can we keep up with the latest release tagged from [the 5.15 branch](https://code.qt.io/cgit/qt/qtwebengine.git/log/?h=5.15)?

We have org.qutebrowser.qutebrowser in Flathub that uses this baseapp, and I bet users will appreciate not using a browser with multiple security vulnerabilities.

**Comment by tinywrkb** [comment]
ping @aleixpol

**Comment by Erick555** [comment]
I don't think there is specific reason it wasn't updated other than nobody volunteered to do so. I don't see published tarballs for latest versions so perhaps it needs to build form git instead.

**Comment by tinywrkb** [comment]
@Erick555 thank! I sent a PR bumping this branch and added f-e-d-c support. No idea if it will build correctly, will let the CI run.
