### ISSUE TITLE
include QtWebView

### ISSUE THREAD

**Issue by kebekus** [flathub/io.qt.qtwebengine.BaseApp#19]
Thank you for this extremely helpful package!

I would like to suggest including the QtWebView module in addition to QtWebEngine. As it stands now, the package does include QtWebEngine, which is arguably the more difficult of the two builds, but does not include the header files required to build the much simpler QtWebView and its plugin for QtWebEngine. 

I maintain an app that uses QtWebView and would be grateful for any ready-made package that I could use.

And again: thank you for providing the package!

**Comment by hfiguiere** [comment]
Doesn't https://github.com/flathub/io.qt.qtwebkit.BaseApp provide it?

**Comment by kebekus** [comment]
Dear hfiguiere, 

thank you for this prompt reply! I fear that the answer is "no". For all I see, QtWebkit is no longer supported and QtWebEngine is the successor.

Best,

Stefan.

**Comment by tinywrkb** [comment]
@kebekus can you try the latest test build from #31?
