### ISSUE TITLE
/app/lib/x86_64-linux-gnu/pkgconfig is missing from PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by ntonnaett** [flathub/io.qt.qtwebengine.BaseApp#205]
Because /app/lib/x86_64-linux-gnu/pkgconfig is missing from the PKG_CONFIG_PATH environment variable, Meson is unable to find Qt modules from the base app.

The workaround I'm using right now is adding it as an additional pkg-config path to the Meson configuration. But it would be great to make this work out of the box.

```json
{
    "name": "jacktrip",
    "buildsystem": "meson",
    "config-opts": [
        "-Dbuildtype=debugoptimized",
        "-Dpkg_config_path=/app/lib/x86_64-linux-gnu/pkgconfig"
    ],
    "sources": [
        {
            "type": "git",
            "url": "https://github.com/jacktrip/jacktrip/",
            "branch": "dev"
        }
    ]
}
```

**Comment by hfiguiere** [comment]
which branch?

**Comment by hfiguiere** [comment]
btw in any case you can use `append-pkg-config-path` to add to the pkg-config path

**Comment by hfiguiere** [comment]
sorry didn't mean to close.

**Comment by ntonnaett** [comment]
6.5, but I switched back to 6.4 later because of flatpak-github-actions.

**Comment by hfiguiere** [comment]
This is not different in 5.15-22.08.

So I'm not sure what the original intent is, but the best for now is to use `append-pkg-config-path`.

**Comment by bbhtt** [comment]
I think this should be added in the wiki or the files symlinked to `/app/lib/pkgconfig`, depending on how to solve this.

There is no easy to make them install in that location without patching qtwebengine.

**Comment by ntonnaett** [comment]
If '/app/lib/x86_64-linux-gnu/pkgconfig' is added to 'PKG_CONFIG_PATH' in the base app, this should work out of the box for all build systems. Is there a reason we wouldn't want to go that route?

**Comment by bbhtt** [comment]
I guess I can do that too, not sure which will be more sensible.

**Comment by bbhtt** [comment]
> I guess I can do that too, not sure which will be more sensible.

Baseapps don't have finish-args. It's treated as a regular app ref and permissions aren't inherited by flatpak when building an app unlike runtimes.

I don't think it'd be possible to add an env variable in the baseapp to make it available for apps.

**Comment by bbhtt** [comment]
I decided to not add workarounds like copying or symlinking, they can cause issues because other baseapps depend on this one or may fail. The wiki has the info that should be enough https://github.com/flathub/io.qt.qtwebengine.BaseApp/wiki#pkgconfig-files
