### ISSUE TITLE
Can't compile application using webenginewidgets on qt6

### ISSUE THREAD

**Issue by adamlamar** [flathub/io.qt.qtwebengine.BaseApp#375]
Hi there,

Thanks for this very useful package!

I'm working on an existing application built with `5.15-23.08` that works as expected.

When I upgrade to `6.7`, the build fails with `Project ERROR: Unknown module(s) in QT: webenginewidgets`. Inspecting the flatpak builddir I see various WebEngineWidget files like the pri, header, and shared objects are present, but for some reason they're not recognized by qmake.

Any suggestions on how I can get the webenginewidgets to be recognized? `QMAKEPATH` is already set.

**Comment by bbhtt** [comment]
What does Qmake do to recognize them? Is it looking for the pkgconfig files?

**Comment by adamlamar** [comment]
No, I'm not an expert but I'm pretty sure its looking for the `.pri` files under `mkspecs`. I see it looking under `/usr/mkspecs` with `strace qmake .`

But good news. I somewhat accidentally set `QMAKEPATH=/app` (not `/app/lib`) and that actually fixed the build. This makes sense if qmake needs the pri files, since there are none under `/app/lib`.

Might be a good idea to advise folks in the wiki to set this for their qmake builds.

**Comment by adamlamar** [comment]
Looks good thank you for the quick turnaround and docs update. For future reference the quick summary is:

5.15: QMAKEPATH=/app/lib
6.x: QMAKEPATH=/app
