### ISSUE TITLE
flatpak-builder fails to locate  libQt5WebEngineWidgets.so in /app/lib/x86_64-linux-gnu

### ISSUE THREAD

**Issue by trappedinspacetime** [flathub/io.qt.qtwebengine.BaseApp#4]
First of all, thank you for maintaining this library.
I want to build [ugene](https://github.com/ugeneunipro/ugene).
I made a manifest file and tried to build it.
It locates libraries for `kde.sdk` but it fails to locate `qtwebengine` libraries under `/app/lib/x86_64-linux-gnu` instead they 
are present in `/usr/lib/x86_64-linux-gnu` which they are not reached by build process.

     {
       "id": "org.kde.UgeneuiPro",
       "runtime": "org.kde.Platform",
       "runtime-version": "5.14",
       "sdk": "org.kde.Sdk",
       "base": "io.qt.qtwebengine.BaseApp",
       "base-version": "5.14",
       "command": "ugeneui",
       "rename-icon": "ugene",
       "finish-args": [
         "--socket=wayland",
         "--socket=x11",
         "--share=ipc",
         "--device=dri",
         "--share=network",
         "--talk-name=org.kde.StatusNotifierWatcher"
       ],
     
       "modules": [
         {
           "name": "ugeneunipro",
     	  "buildsystem": "qmake",
     	  "config-opts": [
                 "INCLUDEPATH+=/app/include",
                 "INCLUDEPATH+=/app/include/QtWebEngineWidgets",
                 "INCLUDEPATH+=/app/include/QtWebEngine",
                 "INCLUDEPATH+=/app/include/QtWebEngineCore",
                 "INCLUDEPATH+=/app/include/pci",
                 "LIBS+=-L/app/lib/x86_64-linux-gnu",
                 "LIBS+=-L/app/lib/x86_64-linux-gnu/libQt5WebEngine.so",
                 "LIBS+=-L/app/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so",
                 "LIBS+=-L/app/lib/x86_64-linux-gnu/libQt5WebEngineCore.so",
                 "QMAKE_LIBDIR+=/app/lib/x86_64-linux-gnu",
                 "QT_PLUGIN_PATH+=/app/lib/x86_64-linux-gnu",
                 "QMAKE_LFLAGS+=-L/app/lib/x86_64-linux-gnu",
                 "QT_WEBENGINE_LIB+=-L/app/lib/x86_64-linux-gnu",
                 "QMAKE_LIBDIR+=/app/lib/x86_64-linux-gnu",
                 "QT += webengine webenginewidgets",
                 "CONFIG+=x64"
             ],
     	  "build-options":{
               "prepend-pkg-config-path": "/app/lib/x86_64-linux-gnu/pkgconfig",
               "prepend-pkg-config-path": "/app/lib/pkgconfig",
     		  "env":{
     			  "QMAKEPATH": "/app/lib",
                   "LDFLAGS": "-L/app/lib/x86_64-linux-gnu",
                   "LD_LIBRARY_PATH": "/app/lib/x86_64-linux-gnu"
     		  }
     	  },
           "sources": [ { "type": "dir", "path": "./ugene" } ]
         }
       ]
     }

**Comment by aleixpol** [comment]
Seems to be the same as #2.

FWIW, I'd recommend using CMake to QMake which is much better tested and I see ugene has both.

**Comment by aleixpol** [comment]
Or rather #1

**Comment by trappedinspacetime** [comment]
@aleixpol They don't maintain `cmake` support anymore #https://github.com/ugeneunipro/ugene/issues/61
